---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: cnb-common
- name: source

outputs:
- name: package

caches:
- path: cnb-packager-cache
- path: go-module-cache

run:
  path: cnb-common/package.sh

params:
  PASSWORD:
  USERNAME:
