---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: latest

inputs:
- name: cnb-common
- name: source

outputs:
- name: package

caches:
- path: go-module-cache

run:
  path: cnb-common/package.sh
